HaloRuns/HaloRuns/Models/ViewModels/RunForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace HaloRuns.Models.ViewModels
{
    public class RunForm
    {
        public RunForm()
        {
        }

        public RunForm(User someone, List<Game> games, List<Difficulty> difficulties)
        {
            this.user = someone;
            this.games = games;
            this.difficulties = difficulties;

        }

        [DisplayName("username")]
        public User user { get; set;}
        public List<Difficulty> difficulties { get; set; }
        public List<Game> games { get; set; }
        public int GameId { get; set; }

        public Run run { get; set;}

        //public string Username { get; set; }
        //public int Date { get; set; }
        //[DisplayName("time")]
        //public int Time { get; set; }
        //[DisplayName("edition")]
        //public int EditionId { get; set; }
        //public int Id { get; set; }
        //[DisplayName("difficulty")]
        //public int DifficultyId { get; set; }
        //public string Url { get; set; }
        //public int MapId { get; set; }
        //public map Map { get; set; }
        //public int UserId { get; set; }
        //public User User { get; set; }
        //public edition Edition { get; set; }
    }
}

HaloRuns/HaloRuns/Models/run.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace HaloRuns.Models
{
    public class Run
    {
        public int Date { get; set; }
        [DisplayName("time")]
        public int Time { get; set; }
        [DisplayName("edition")]
        public int EditionId { get; set; }
        public int Id { get; set; }
        [DisplayName("difficulty")]
        public int DifficultyId { get; set; }
        public Difficulty Difficulty { get; set; }
        public string Url { get; set; }
        public int MapId { get; set; }
        public Map Map { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
        public Edition Edition { get; set;}
        public int GameId { get; set; }
    }
}

HaloRuns/HaloRuns/Controllers/RunsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HaloRuns.Models;
using Microsoft.AspNetCore.Mvc;

namespace HaloRuns.Controllers
{
    public class RunsController : BaseController<Run>
    {
        public RunsController(HaloRunsDbContext param)
            : base(param)
        {
            //user.name, Map.name, Time

            lambdas = new List<Func<Run, object>> { 
                run => run.User.Username,
                run => run.Map.name,
                run => run.Time,
            }; 
        }
        /*
        public RunsDatatableParam SetRunTable(run r) {
            var rTable = new RunsDatatableParam();
            rTable.Date = r.Date;
            rTable.Time = r.Time;
            rTable.Id = r.Id;
            return rTable;
        }
        */
        public IActionResult Index()
        {
            /*var list = db
                .Runs
                .ToList()
                .Select(r => new RunsDatatableParam { Date = r.Date, Time = r.Time, Id = r.Id});
            */
                
            return View();
        }
        public ViewResult Table()
        {
            return View();

        }
        /*
        public class RunsDatatableParam
        {
            public int Date { get; set; }

            public int Time{ get; set; }

            public int Id { get; set; }

        }
        */
        public override JsonResult dataTableParam()
        {
            return generateDataTablesParam<RunsDatatableParam>();
        }

    }

}

HaloRuns/HaloRuns/Views/Runs/Table.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
        public int Date { get; set; }
        [DisplayName("time")]
        public int Time { get; set; }
        [DisplayName("edition")]
        public int EditionId { get; set; }
        public int Id { get; set; }
        [DisplayName("difficulty")]
        public int DifficultyId { get; set; }
        public string Url { get; set; }
        public int MapId { get; set; }
        public map Map { get; set; }
        public int UserId { get; set; }
*@

@section title{Runs}

@model HaloRuns.Models.Run
<button type ="button" id="runbutton">
    Click
</button>

<table style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(r => r.Id)
            </th>
            <th>
                @Html.DisplayNameFor(r => r.Date)
            </th>
            <th>
                @Html.DisplayNameFor(r => r.Time)
            </th>
            <th>
                @Html.DisplayNameFor(r => r.Edition.Name)
            </th>
        </tr>
    </thead>
</table>

@section Scripts{ 
    <script>
        $(document).ready(function () {
            $.get('@(Url.Action("dataTableParam", "Runs"))', null, function (data) {
                var table = $('table').DataTable(data);
            })
        })
        /*function buttonclickcallback() {
            console.log("button has been clicked");
        }
        function registerButtonEventHandler() {
            $('#runbutton').mouseup(buttonclickcallback);
        }
        */
        @*
        $(document).ready(function () {
            var table = $('table').DataTable({
                "searching" : false,
                "bPaginate": true,
                "bLengthChange": false,
                "bFilter": true,
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": "@Url.Action("DataTablesCallback", "Runs")",
                    "type": "POST",
                    "datatype": "json",
                },
                "bInfo": false,
                "bAutoWidth": true,
                "order": [[1, "asc"]],
            });
        });
        *@
        $(document).ready(function ()
        {
            $('#runbutton').mouseup(function () {
                console.log("button has been clicked");
            });
        });
        //$(document).ready(initalizeDataTables);
        //$(document).ready(registerButtonEventHandler);
    </script>
} 
